Repository Vaultionizer/vault-server, pull requests merged in 2020-11, with the labels that each got.

#4 Feature/swagger setup
  src/main/java/com/vaultionizer/vaultserver/config/SwaggerConfig.java
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
Labels: enhancement

#5 Feature/unit tests
  scripts/build_project_docker.sh
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
  src/main/java/com/vaultionizer/vaultserver/helpers/Config.java
  src/main/java/com/vaultionizer/vaultserver/model/db/RefFilesModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/SessionModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/SpaceModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserAccessModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserModel.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/CreateSpaceDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/GenericAuthDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/JoinSpaceDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/LoginUserDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/RegisterUserDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/SpaceAuthKeyDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/SpaceAuthKeyResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/resource/SpaceRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserAccessRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/UserAccessService.java
  src/test/java/com/vaultionizer/vaultserver/TestHelpers.java
  src/test/java/com/vaultionizer/vaultserver/controllers/SpaceControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/controllers/UserControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/testdata/SpaceTestData.java
  src/test/java/com/vaultionizer/vaultserver/testdata/UserTestData.java
Labels: enhancement

#7 Added https support. Key can be generated with script.
  .gitignore
  Dockerfile
  docker-compose.yml
  scripts/create_tls_key.sh
  src/main/java/com/vaultionizer/vaultserver/VaultserverApplication.java
  src/main/java/com/vaultionizer/vaultserver/config/SecurityConfig.java
  src/main/java/com/vaultionizer/vaultserver/controllers/MiscController.java
  src/main/java/com/vaultionizer/vaultserver/helpers/Config.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/GetVersionResponseDto.java
  src/main/resources/application.properties
  src/test/java/com/vaultionizer/vaultserver/VaultserverApplicationTests.java
  src/test/java/com/vaultionizer/vaultserver/controllers/MiscControllerTest.java
Labels: enhancement

#6 Feature/GitHub actions
  .github/workflows/maven.yml
Labels: enhancement

#9 Feature/websocket upload
  pom.xml
  src/main/java/com/vaultionizer/vaultserver/VaultserverApplication.java
  src/main/java/com/vaultionizer/vaultserver/config/SecurityConfig.java
  src/main/java/com/vaultionizer/vaultserver/config/WebSocketChannelFilter.java
  src/main/java/com/vaultionizer/vaultserver/config/WebSocketConfig.java
  src/main/java/com/vaultionizer/vaultserver/controllers/FileController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/WebsocketController.java
  src/main/java/com/vaultionizer/vaultserver/helpers/Config.java
  src/main/java/com/vaultionizer/vaultserver/model/db/PendingUploadModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/RefFilesModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/SessionModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserModel.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/FileUploadDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/FileUploadWebsocketDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/GenericAuthDto.java
  src/main/java/com/vaultionizer/vaultserver/resource/PendingUploadRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SessionRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SpaceRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/FileService.java
  src/main/java/com/vaultionizer/vaultserver/service/PendingUploadService.java
  src/main/java/com/vaultionizer/vaultserver/service/RefFileService.java
  src/main/java/com/vaultionizer/vaultserver/service/SessionService.java
  src/main/java/com/vaultionizer/vaultserver/service/SpaceService.java
  src/test/java/com/vaultionizer/vaultserver/controllers/UserControllerTest.java
Labels: delete branch, enhancement

#8 try adding caching to workflow
  .github/workflows/maven.yml
Labels: DO_NOT_MERGE, conserve branch

#10 Continuous release
  .github/workflows/maven.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  pom.xml
  scripts/build_project_docker.sh
  scripts/create_tls_key.sh
  src/main/java/com/vaultionizer/vaultserver/VaultserverApplication.java
  src/main/java/com/vaultionizer/vaultserver/config/SecurityConfig.java
  src/main/java/com/vaultionizer/vaultserver/config/SwaggerConfig.java
  src/main/java/com/vaultionizer/vaultserver/config/WebSocketChannelFilter.java
  src/main/java/com/vaultionizer/vaultserver/config/WebSocketConfig.java
  src/main/java/com/vaultionizer/vaultserver/controllers/FileController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/MiscController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/WebsocketController.java
  src/main/java/com/vaultionizer/vaultserver/helpers/Config.java
  src/main/java/com/vaultionizer/vaultserver/helpers/SessionTokenGen.java
  src/main/java/com/vaultionizer/vaultserver/model/UserModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/PendingUploadModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/RefFilesModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/SessionModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/SpaceModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserAccessModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserModel.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/CreateSpaceDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/FileUploadDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/FileUploadWebsocketDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/GenericAuthDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/GetSpacesResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/GetVersionResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/JoinSpaceDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/LoginUserDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/LoginUserResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/RegisterUserDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/RegisterUserResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/SpaceAuthKeyDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/SpaceAuthKeyResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/resource/PendingUploadRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/RefFileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SessionRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SpaceRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserAccessRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/FileService.java
  src/main/java/com/vaultionizer/vaultserver/service/PendingUploadService.java
  src/main/java/com/vaultionizer/vaultserver/service/RefFileService.java
  src/main/java/com/vaultionizer/vaultserver/service/SessionService.java
  src/main/java/com/vaultionizer/vaultserver/service/SpaceService.java
  src/main/java/com/vaultionizer/vaultserver/service/UserAccessService.java
  src/main/resources/application.properties
  src/test/java/com/vaultionizer/vaultserver/TestHelpers.java
  src/test/java/com/vaultionizer/vaultserver/VaultserverApplicationTests.java
  src/test/java/com/vaultionizer/vaultserver/controllers/MiscControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/controllers/SpaceControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/controllers/UserControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/testdata/SpaceTestData.java
  src/test/java/com/vaultionizer/vaultserver/testdata/UserTestData.java
Labels: enhancement

#11 Update README.md
  .github/workflows/maven.yml
  README.md
Labels: delete branch

#13 Create docker-publish-master.yml
  .github/workflows/build-test-dev-master.yml
  .github/workflows/docker-publish-develop.yml
  .github/workflows/docker-publish-master.yml
Labels: delete branch

#12 Feature/download file
  src/main/java/com/vaultionizer/vaultserver/config/SecurityConfig.java
  src/main/java/com/vaultionizer/vaultserver/config/WebSocketChannelFilter.java
  src/main/java/com/vaultionizer/vaultserver/config/WebSocketConfig.java
  src/main/java/com/vaultionizer/vaultserver/controllers/FileController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/MiscController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/RefFileController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/SessionController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/WebsocketController.java
  src/main/java/com/vaultionizer/vaultserver/helpers/Config.java
  src/main/java/com/vaultionizer/vaultserver/helpers/FileStatus.java
  src/main/java/com/vaultionizer/vaultserver/model/db/FileModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/RefFilesModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/SessionModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserAccessModel.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/CreateSpaceDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/DeleteFileDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/FileDownloadDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/FileUploadWebsocketDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/GenericAuthDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/LoginUserResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/ReadRefFileDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/RegisterUserResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/UpdateRefFileDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/WebsocketFileDto.java
  src/main/java/com/vaultionizer/vaultserver/resource/FileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/PendingUploadRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/RefFileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SessionRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SpaceRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/FileService.java
  src/main/java/com/vaultionizer/vaultserver/service/RefFileService.java
  src/main/java/com/vaultionizer/vaultserver/service/SessionService.java
  src/test/java/com/vaultionizer/vaultserver/VaultserverApplicationTests.java
  src/test/java/com/vaultionizer/vaultserver/controllers/SpaceControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/controllers/UserControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/testdata/UserTestData.java
Labels: delete branch

#14 Update docker-publish-develop.yml
  .github/workflows/docker-publish-develop.yml
Labels: delete branch

#15 Update docker-publish-develop.yml
  .github/workflows/docker-publish-develop.yml
  .github/workflows/docker-publish-master.yml
Labels: delete branch

#16 Feature/username
  src/main/java/com/vaultionizer/vaultserver/config/SecurityConfig.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/WebsocketController.java
  src/main/java/com/vaultionizer/vaultserver/helpers/Config.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserModel.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/LoginUserDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/RegisterUserDto.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/UserService.java
  src/test/java/com/vaultionizer/vaultserver/controllers/UserControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/testdata/UserTestData.java
Labels: delete branch

#17 VAULTIONIZER-104 Environment variables for testing purposes
  Dockerfile
  scripts/build_project_docker.sh
  src/main/resources/application.properties
Labels: enhancement

#19 Fix deletion (VAULTIONIZER-104)
  Dockerfile
Labels: bug

#22 VAULTIONIZER-108 Add type annotation to support more than 255 characters
  src/main/java/com/vaultionizer/vaultserver/model/db/RefFilesModel.java
Labels: bug

#24 Feature/deletion
  .gitignore
  docker-compose.yml
  src/main/java/com/vaultionizer/vaultserver/controllers/SessionController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
  src/main/java/com/vaultionizer/vaultserver/helpers/Config.java
  src/main/java/com/vaultionizer/vaultserver/jobs/PendingUploadJob.java
  src/main/java/com/vaultionizer/vaultserver/jobs/SessionJob.java
  src/main/java/com/vaultionizer/vaultserver/model/db/FileModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/PendingUploadModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/RefFilesModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/SessionModel.java
  src/main/java/com/vaultionizer/vaultserver/model/db/UserAccessModel.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/AuthWrapperDto.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/ReadRefFileDto.java
  src/main/java/com/vaultionizer/vaultserver/resource/FileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/PendingUploadRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/RefFileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SessionRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SpaceRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserAccessRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/FileService.java
  src/main/java/com/vaultionizer/vaultserver/service/PendingUploadService.java
  src/main/java/com/vaultionizer/vaultserver/service/RefFileService.java
  src/main/java/com/vaultionizer/vaultserver/service/SessionService.java
  src/main/java/com/vaultionizer/vaultserver/service/SpaceService.java
  src/main/java/com/vaultionizer/vaultserver/service/UserAccessService.java
  src/main/java/com/vaultionizer/vaultserver/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/vaultionizer/vaultserver/controllers/SpaceControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/controllers/UserControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/testdata/SpaceTestData.java
Labels: delete branch

#25 Feature/quit space
  src/main/java/com/vaultionizer/vaultserver/controllers/FileController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/resource/FileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/PendingUploadRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/RefFileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SessionRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/SpaceRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserAccessRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/UserRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/SpaceService.java
  src/main/java/com/vaultionizer/vaultserver/service/UserAccessService.java
Labels: delete branch, enhancement

#26 Cleaned up architectual inconsistencies.
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
  src/main/java/com/vaultionizer/vaultserver/model/dto/RegisterUserResponseDto.java
  src/main/java/com/vaultionizer/vaultserver/service/RefFileService.java
  src/main/java/com/vaultionizer/vaultserver/service/SessionService.java
  src/main/java/com/vaultionizer/vaultserver/service/SpaceService.java
  src/main/java/com/vaultionizer/vaultserver/service/UserService.java
  src/test/java/com/vaultionizer/vaultserver/controllers/SpaceControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/controllers/UserControllerTest.java
  src/test/java/com/vaultionizer/vaultserver/testdata/UserTestData.java
Labels: delete branch

#27 Add cucumber support
  pom.xml
  src/test/java/com/vaultionizer/vaultserver/CucumberIntegrationTest.java
  src/test/java/com/vaultionizer/vaultserver/cucumber/steps/TestStep.java
  src/test/resources/features/test.feature
Labels: enhancement

#28 Feature/cucumbaaa
  src/main/java/com/vaultionizer/vaultserver/controllers/SpaceController.java
  src/main/java/com/vaultionizer/vaultserver/controllers/UserController.java
  src/main/java/com/vaultionizer/vaultserver/resource/FileRepository.java
  src/main/java/com/vaultionizer/vaultserver/resource/PendingUploadRepository.java
  src/main/java/com/vaultionizer/vaultserver/service/FileService.java
  src/main/java/com/vaultionizer/vaultserver/service/PendingUploadService.java
  src/test/java/com/vaultionizer/vaultserver/cucumber/steps/CreateSpaceSteps.java
  src/test/java/com/vaultionizer/vaultserver/cucumber/steps/CreateUserSteps.java
  src/test/java/com/vaultionizer/vaultserver/cucumber/steps/DeleteSpaceSteps.java
  src/test/java/com/vaultionizer/vaultserver/cucumber/steps/Services.java
  src/test/java/com/vaultionizer/vaultserver/cucumber/steps/TestStep.java
  src/test/resources/features/createSpace.feature
  src/test/resources/features/createUser.feature
  src/test/resources/features/deleteSpace.feature
  src/test/resources/features/test.feature
Labels: delete branch
